### ISSUE TITLE
Possibility to select the bcache device of the TUI

### ISSUE THREAD

**Issue by 6ax** [quantum/esos#208]
Of course you can do so, `scstadmin -open_dev bcache0 -handler vdisk_fileio -attributes filename=/dev/bcache0,blocksize=4096,nv_cache=1`
but through the TUI is much more convenient. 

Tnx.

**Comment by msmith626** [comment]
This has been resolved in the 'master' branch (79fe629a89ab60f5ed1aa57b37ff62a30dbc0a9f); this change will be merged into 2.x.x in the coming weeks for a 2.1.x release.

--Marc
