### ISSUE TITLE
dmideode needs patch

### ISSUE THREAD

**Issue by mahiryaylacioglu** [quantum/esos#226]
dmidecode
# dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.
Table at 0x000EA000.

/sys/firmware/dmi/tables/DMI: Unexpected end of file
Table is unreachable, sorry.

can u please include patches from http://dmidecode.nongnu.org/ to fix this?

**Comment by msmith626** [comment]
Hi,

You will need to use the ESOS packages from the "master" branch which uses
dmidecode version 3.2.

--Marc
