### ISSUE TITLE
Modifying file system causes kernel panic

### ISSUE THREAD

**Issue by githublti** [quantum/esos#228]
Trying to update the file system on ESOS 1.3.10 to include Midnight Commander following this link

https://github.com/quantum/esos/wiki/24_System_Customization#modifying-files-on-the-root-file-system

Will result in a kernel panic on modification.

I mounted root
I created a mount point in temp
I mounted with archivemount

Initially, I copied the mc binary into /usr/bin and the needed libraries into /lib, unmounted the temporary mount point and waited the 3 or so minutes until archivemount was no longer in the process list.

After that I unmounted /mnt/root and then rebooted.  On restart, I get a kernel panic after it gets to the point of waiting for devices to settle.

   Kernel panic - not syncing:  Attempted to kill init!  exitcode=0x00000100

Rebuilt 1.3.10 again, this time I only copied the mc binary to the /tmp/cpio_image/bin directory, unmount and wait again for the archivemount process to complete and unmount /mnt/root and reboot.

Kernel panic again.

Are the instructions on the link outdated?

Thanks,

Doug Lytle

**Comment by msmith626** [comment]
Hi Doug,

No, the instructions are up-to-date, however, it's been known that archivemount / libarchive do not always work as expected, and therefore, we don't have good luck with modifying the CPIO archive in-place. I've found it works best on systems with lots of memory, but even then, it's not 100%.

I expect we'll move to a different image format in the future, I think CPIO is a bit dated (but still does trick). And perhaps then we can use different tools to modify these images in-place.

For now, it might be best to build ESOS from source, and inject whatever is needed into the 'work/chroot/' directory structure after running chroot_build.sh, then build an image ('sudo make image').

--Marc

**Comment by githublti** [comment]
Thanks Marc!

That's exactly what I did.  Took a bit, but I now have at working install with Midnight Commander,

Doug
