### ISSUE TITLE
ESOS download

### ISSUE THREAD

**Issue by pitt2k** [quantum/esos#231]
Hi,

The website download.esos-project.com does not work.
I cannot download ESOS in any way.
Please fix it asap.

Thanks,
p.

**Comment by msmith626** [comment]
Hi,

Sorry for the inconvenience -- we are working to resolve this as quickly as
possible.

--Marc

**Comment by pitt2k** [comment]
Hi,
Now the whole project site is down. While you're in the process of fixing it, can you please paste a direct link to download the latest ESOS 2.x to boot up from USB please?

Thanks,
p.

**Comment by msmith626** [comment]
Hi,

The download page DNS has been fixed: http://download.esos-project.com

Working on the project info page still...

--Marc

**Comment by msmith626** [comment]
All web services have been restored, sorry for the inconvenience!
