### ISSUE TITLE
Should use 'clean' instead of 'distclean' in Makefile.in for the nginx target

### ISSUE THREAD

**Issue by mihsu81** [quantum/esos#233]
The nginx.chroot target in **_Makefile.in_** references "distclean" but the nginx **_init_** file needs "clean".

**_Makefile.in_**
"nginx.chroot: glibc.chroot pcre.chroot zlib.chroot openssl.chroot
	$(QUIET) $(ECHO) "### Building $(@)"
	$(call chroot_only)
	cd $(tgt_src_dir) && ./configure --prefix=/var/lib/nginx \
	--sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf \
	--pid-path=/var/run/nginx.pid \
	--error-log-path=/var/log/nginx/error.log \
	--http-log-path=/var/log/nginx/access.log \
	--with-http_ssl_module
	$(MAKE) --directory=$(tgt_src_dir)
	$(MAKE) --directory=$(tgt_src_dir) install
	$(MAKE) --directory=$(tgt_src_dir) **_distclean_**
	$(TOUCH) $(@)
	$(QUIET) $(ECHO) "### Done $(@)""

**_/.../esos/work/chroot/sources/nginx-1.16.0/auto/init_**
"# create Makefile

cat << END > Makefile

default:	build

**_clean:_**
	rm -rf Makefile $NGX_OBJS
END"

**Comment by msmith626** [comment]
Thank you for finding this, I'll fix this in next push.

Does this mean you were able to overcome your bootstrap / perl build issue?

**Comment by mihsu81** [comment]
> Thank you for finding this, I'll fix this in next push.
I'm glad i could help
> 
> Does this mean you were able to overcome your bootstrap / perl build issue?
Not yet, but it didn't seem to have any impact on the build. I'm still testing the build though.

**Comment by mihsu81** [comment]
> Thank you for finding this, I'll fix this in next push.
> 
> Does this mean you were able to overcome your bootstrap / perl build issue?

I'm glad i could help.
Didn't get to the bottom of that bootstrap/perl issue, but it didn't seem to have any impact on the build. I'm still testing the build though.

**Comment by msmith626** [comment]
This has been resolved.
