### ISSUE TITLE
dev_tape not working on 2.0.0

### ISSUE THREAD

**Issue by sub205** [quantum/esos#234]
I upgraded to esos 2.0.0 with my iscsi san that's just exporting a tandberg lto6 to a windows 2012r2 client for backup. The client is running veritas backup exec 16. After upgrading and reconfiguring esos, the drive is found but gets pulled offline with an io-error.

Reverting back to 1.3.9 fixes the problem.

The drive is connected to an adaptec 5805 controller and works fine.
Exporting volumes via vdisk_blockio also works fine, it's just an issue with the tape that is directly related to the version of esos.

I checked the changelogs but was unable to find anything.

**Comment by msmith626** [comment]
Hmm... those two versions do use a different SCST version. Any logs available? Namely kernel logs from the 2.0.0 system when you attempt to use dev_tape would be a good start.

--Marc

**Comment by sub205** [comment]
Kernellog is useless, it's just displaying that it's requesting the sensecode (which is neither shown or logged somewhere) - the windows-host using the tape is logging cdb 8 sense 0 asc 0 ascq 0 which is completely unspecific.
Some commands and programms seem to work, but f.e. veritas backup exec fails entirely. At first i suspected the drive, changed it and did a reinstall of esos. But only reverting back to 1.x helped.

**Comment by msmith626** [comment]
Anything useful on the scst-devel mailing list? May be worthwhile asking
there, as it sounds like this is something specific to SCST. Both 1.3.9 and
2.0.0 use SCST 3.3.x but 2.0.0 uses r7994, and 1.3.9 uses r7271. Those are
pretty close, and in the same branch, so I wouldn't think any major changes
exist.

--Marc
