### ISSUE TITLE
Malformed Makefile line in 1.x.x repo

### ISSUE THREAD

**Issue by dswartz** [quantum/esos#240]
Top level Makefile;

nvmetcli.chroot: Python.chroot setuptools.chroot configshell-fb.chroot \
        six.chroot pyparsing.chroot
The 'six.chroot' line has spaces at the beginning, and not a tab.  No idea if this breaks anything, but emacs complains :)

**Comment by msmith626** [comment]
Hi Dan,

Thanks for pointing this out; the '1.x.x' branch as been deprecated, so no need to keep this open.

--Marc

**Comment by dswartz** [comment]
But master is unstable.  Is there a stable release to build against?

On December 21, 2019, at 11:10 PM, "Marc A. Smith" <notifications@github.com> wrote:

Hi Dan,

Thanks for pointing this out; the '1.x.x' branch as been deprecated, so no need to keep this open.

--Marc

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/quantum/esos/issues/240?email_source=notifications">https://github.com/quantum/esos/issues/240?email_source=notifications</a>\u0026email_token=AATWNNUGYHFZ43DELVRSLCTQZ3SA3A5CNFSM4J6HWWM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPIJRA#issuecomment-568231108", "url": "<a href="https://github.com/quantum/esos/issues/240?email_source=notifications">https://github.com/quantum/esos/issues/240?email_source=notifications</a>\u0026email_token=AATWNNUGYHFZ43DELVRSLCTQZ3SA3A5CNFSM4J6HWWM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPIJRA#issuecomment-568231108", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by msmith626** [comment]
How do you know it's unstable if you can't build it? Try using a modern Fedora system to build... I've asked a fellow to help revamp the build stuff for ESOS, and get a container going so builds are easier for others. Anyhow, 'master' is probably considered unstable anyhow (eg, bleeding edge). The '2.x.x' branch is current release branch.

**Comment by dswartz** [comment]
I meant its called unstable.  Should I not trust the name?

On December 21, 2019, at 11:26 PM, "Marc A. Smith" <notifications@github.com> wrote:

How do you know it's unstable if you can't build it? Try using a modern Fedora system to build... I've asked a fellow to help revamp the build stuff for ESOS, and get a container going so builds are easier for others. Anyhow, 'master' is probably considered unstable anyhow (eg, bleeding edge). The '2.x.x' branch is current release branch.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/quantum/esos/issues/240?email_source=notifications">https://github.com/quantum/esos/issues/240?email_source=notifications</a>\u0026email_token=AATWNNVVHRXZB4CFEJTL6P3QZ3T5HA5CNFSM4J6HWWM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPIN4Y#issuecomment-568231667", "url": "<a href="https://github.com/quantum/esos/issues/240?email_source=notifications">https://github.com/quantum/esos/issues/240?email_source=notifications</a>\u0026email_token=AATWNNVVHRXZB4CFEJTL6P3QZ3T5HA5CNFSM4J6HWWM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPIN4Y#issuecomment-568231667", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by dswartz** [comment]
I see what confused me.  The downloads page has a to 2.x.x but doesn't explain it.  I'll give that a try...

On December 21, 2019, at 11:26 PM, "Marc A. Smith" <notifications@github.com> wrote:

How do you know it's unstable if you can't build it? Try using a modern Fedora system to build... I've asked a fellow to help revamp the build stuff for ESOS, and get a container going so builds are easier for others. Anyhow, 'master' is probably considered unstable anyhow (eg, bleeding edge). The '2.x.x' branch is current release branch.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/quantum/esos/issues/240?email_source=notifications">https://github.com/quantum/esos/issues/240?email_source=notifications</a>\u0026email_token=AATWNNVVHRXZB4CFEJTL6P3QZ3T5HA5CNFSM4J6HWWM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPIN4Y#issuecomment-568231667", "url": "<a href="https://github.com/quantum/esos/issues/240?email_source=notifications">https://github.com/quantum/esos/issues/240?email_source=notifications</a>\u0026email_token=AATWNNVVHRXZB4CFEJTL6P3QZ3T5HA5CNFSM4J6HWWM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHPIN4Y#issuecomment-568231667", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by dswartz** [comment]
On 2019-12-21 23:25, Marc A. Smith wrote:
> How do you know it's unstable if you can't build it? Try using a
> modern Fedora system to build... I've asked a fellow to help revamp
> the build stuff for ESOS, and get a container going so builds are
> easier for others. Anyhow, 'master' is probably considered unstable
> anyhow (eg, bleeding edge). The '2.x.x' branch is current release
> branch.

Sorry to be crabby here, but it's very frustrating to have old/outdated 
information on your site, and then have you tell me I'm doing the wrong 
thing :(

You are saying 2.x.x is current branch?  Okay, I am in the middle of 
building against that.  But, even though there is a link to 2.x.x on the 
Downloads page, said page never mentions 2.x.x and still refers to 1.x.x 
as the current stable branch, and says nothing about being deprecated.  
How was I supposed to know?

**Comment by msmith626** [comment]
Please, help contribute then. It's all out of date, and needs some TLC.

**Comment by dswartz** [comment]
On 2019-12-21 23:25, Marc A. Smith wrote:
> How do you know it's unstable if you can't build it? Try using a
> modern Fedora system to build... I've asked a fellow to help revamp
> the build stuff for ESOS, and get a container going so builds are
> easier for others. Anyhow, 'master' is probably considered unstable
> anyhow (eg, bleeding edge). The '2.x.x' branch is current release
> branch.

"Modern Fedora system".  I tried the latest (31).  Pulled down 2.x.x.

    31  git clone https://github.com/parodyne/esos.git
    32  cd esos/
    33  git checkout 2.x.x
    34  autoconf
    35  ./configure --enable-zfs
    36  sudo make symlink
    37  make -j5 -w -Orecurse

(exactly per the documentation), and...

(elided)

generic/comb_tables.c to mpn/comb_tables.c
config.status: linking 
/home/dswartz/esos/work/chroot/sources/gcc-9.1.0/gmp/mpn/generic/add_n_sub_n.c 
to mpn/add_n_sub_n.c
config.status: linking 
/home/dswartz/esos/work/chroot/sources/gcc-9.1.0/gmp/mpn/generic/gmp-mparam.h 
to gmp-mparam.h
config.status: executing libtool commands
configure: summary of build options:

   Version:           GNU MP 6.1.2
   Host type:         none-pc-linux-gnu
   ABI:               standard
   Install prefix:    /tools
   Compiler:          gcc
   Static libraries:  yes
   Shared libraries:  no

make[3]: Leaving directory '/home/dswartz/esos/work/gcc-build'
make[2]: *** [Makefile:940: all] Error 2
make[2]: Leaving directory '/home/dswartz/esos/work/gcc-build'
make[1]: *** [Makefile:769: gcc.pass1] Error 2
make[1]: Leaving directory '/home/dswartz/esos'
make: *** [Makefile:562: all] Error 2
make: Leaving directory '/home/dswartz/esos'

With ZERO useful information.  In the other message, you suggested I 
contribute updating the docs.  Kinda hard when I don't know what the 
**** is the right answer, no?  I've asked more than once, I think, for a 
description of your buildbot, to no avail.  Why you provide all kinds of 
other features baked in, but not ZFS?  Beats the hell out of me, and I 
no longer care.  I've wasted days trying to build a usable ESOS install 
with ZFS, and I'm done.  Good luck moving forward...
