### ISSUE TITLE
Last binary build from mars 2019?

### ISSUE THREAD

**Issue by direktornswe** [quantum/esos#246]
Hi, 
Is this project dead? The last binary build seems close to a year old now?

**Comment by msmith626** [comment]
Definitely still alive and kicking! Check out the commit activity to see source changes: https://github.com/quantum/esos/graphs/commit-activity

Will work on getting the Buildbot software back up and running so new images are posted automatically. In the mean time, building from source is your best bet to try out the latest: https://github.com/quantum/esos/wiki/11_Building

--Marc

**Comment by direktornswe** [comment]
Thanks. 
I've tried building from the "master" branch on CentOS 7.7 but it complains about make :( 

** These critical programs are missing or too old: make
*** Check the INSTALL file for required versions.

So I checked INSTALL and it does not specify GCC version :(

**Comment by msmith626** [comment]
Try a modern Linux distro (like newest Fedora/Ubuntu desktop versions).
