### ISSUE TITLE
Adding control for Lenovo SA120

### ISSUE THREAD

**Issue by direktornswe** [quantum/esos#247]
I've got two of these enclosures with a total of 24 drives. One is connected to a windows host where I can control the RPM of the fans with a Windows tool. However the other enclosure is connected to ESOS and I'd like to be able to install the following tool. Would that be possible? 

https://github.com/AndrewX192/lenovo-sa120-fanspeed-utility

**Comment by msmith626** [comment]
You could try putting that script into '/opt/sbin/' on a running ESOS
machine, then run "conf_sync.sh" and this file will persist across reboots.
The sg3_utils tools are already installed.

--Marc

**Comment by direktornswe** [comment]
Thanks @msmith626 
I couldn't find sg3_utils, is it not in PATH?

**Comment by msmith626** [comment]
"sg3_utils" is the name of a software package, and it looks like "sg_ses" is the tool that software you mentioned above uses. If you continue to have trouble, please try the 'esos-users' Google Group -- you'll get a wider audience vs. GH Issues.
