### ISSUE TITLE
fio: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by izomorph** [quantum/esos#259]
Installed esos 2.0.16 on machine with Xeon X5670 (Westmere EP). Trying to start fio from shell I get error: Illegal instruction (core dumped).
With esos 1.3.9 all works fine.
Maybe this is the cause https://github.com/axboe/fio/issues/946 ?
Could you configure fio with --disable-native in future builds please?

**Comment by msmith626** [comment]
I've hit this before with 'fio' when doing one-off builds on my local machine... and it's escaping me right now on what the solution was. I assume you are using one of the vanilla builds from the downloads area? Or is this a custom image?

**Comment by izomorph** [comment]
I'm using builds from esos-project.com

**Comment by izomorph** [comment]
Thank you! Fio working now in the latest master build.
Tried building esos from source. Succeded to build bootstrap only yesterday. Executing chroot_build.sh now. Later will check would it work too.
