### ISSUE TITLE
RFE:  factory / configuration reset

### ISSUE THREAD

**Issue by devZer0** [quantum/esos#263]
i'm missing an option to reset esos configuration to defaults, without reinstall. 

e.g. after changing HBA, esos is unusable because scst does not even load

**Comment by msmith626** [comment]
If you swapped out an HBA, it's probably easiest to update the FC target WWN values in the '/etc/scst.conf' file. But to answer your question, you can "start fresh" by doing the following:
mount /mnt/conf
rm -rf /mnt/conf/*
umount /mnt/conf
echo b > /proc/sysrq-trigger

This will delete any configuration data in the LABEL=esos_conf file system and then by forcing an immediate reboot (not via init) this ensures the config won't get resync'd during a proper shutdown/reboot. When the system boots up, it will be an unconfigured ESOS instance (assuming all went well with those steps).

--Marc

**Comment by devZer0** [comment]
thanks!
