### ISSUE TITLE
Emulex ocs sdk

### ISSUE THREAD

**Issue by mgdmiller** [quantum/esos#264]
Hi! I am very interested in your project, but my servers use Emulex LPe12000 equipment. As I understood from the documentation for the assembly with the ability to work with this equipment, I need the "emulex ocs sdk" package. But I cannot find this package. Where can I download it?

**Comment by msmith626** [comment]
Hi,

Thanks for reaching out. For the Emulex OCS SDK target driver, you would need reach out to Broadcom (Emulex) and request this as it's not distributed publicly AFAIK.

--Marc
