### ISSUE TITLE
How to replace FC target ?

### ISSUE THREAD

**Issue by xt610zen** [quantum/esos#267]
Now I only have one FC target. If the FC target  are broken, how to replace it? Still need two FC  HBA to join the group,

When one FC does not work, replace it with a new join group?

**Comment by msmith626** [comment]
Stop SCST, then modify the '/etc/scst.conf' file with the new Fibre Channel
HBA WWPN values (target names), and finally start SCST.

**Comment by xt610zen** [comment]
I can't find the '/etc/scst.conf' file in 3.0.5 version ，just see it in  old 1.x.x version

**Comment by msmith626** [comment]
It doesn’t exist until you add SCST items using the TUI or you write the
file with scstadmin.
